<h1>List of sections</h1>
<?php if (sizeof($this -> sections) > 0): ?>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this -> sections as $section): ?>
        <tr>
            <td><?php echo $section -> getId(); ?></td>
            <td><?php echo $section -> getTitle(); ?></td>
            <td><?php echo $section -> getBody(); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p>No sections have been added.</p>
<?php endif; ?>